"""
simulator/ride_simulator.py
===========================
Generates realistic ride request events for 3 cities and 50 zones.

Simulates:
- Time-based demand patterns (rush hour, late night, lunch)
- Weather impact on demand and supply
- Special events (concerts, sports games)
- US public holidays
- Random demand spikes

Each event is a dictionary representing one ride request
that gets published to Kafka by kafka_producer.py
"""

from __future__ import annotations

import random
import time
import uuid
from datetime import datetime
from typing import Generator

import pygeohash as pgh
import pytz
from loguru import logger

from config.settings import settings


# =============================================================================
# ZONE GENERATION
# =============================================================================

def generate_zones(city: object) -> list[dict]:
    """
    Generate geo-hashed zones around a city center.

    Each zone is a geohash string representing a ~1km² area.
    Zones are generated by offsetting from the city center.

    Args:
        city: CityConfig object with lat, lon, num_zones

    Returns:
        List of zone dictionaries with zone_id and coordinates
    """
    zones = []
    # Generate zones in a grid pattern around city center
    offsets_per_side = int(city.num_zones ** 0.5) + 1

    for i in range(-offsets_per_side, offsets_per_side):
        for j in range(-offsets_per_side, offsets_per_side):
            if len(zones) >= city.num_zones:
                break

            # Offset ~0.01 degrees ≈ 1km
            lat = city.latitude + (i * 0.01)
            lon = city.longitude + (j * 0.01)

            zone_id = pgh.encode(lat, lon, precision=6)

            zones.append({
                "zone_id": zone_id,
                "city": city.name,
                "latitude": lat,
                "longitude": lon,
            })

        if len(zones) >= city.num_zones:
            break

    return zones[:city.num_zones]


# =============================================================================
# TIME MULTIPLIERS
# =============================================================================

def get_time_multiplier(local_hour: int, day_of_week: int) -> float:
    """
    Calculate demand multiplier based on time of day and day of week.

    Args:
        local_hour: Hour in local city time (0-23)
        day_of_week: 0=Monday, 6=Sunday

    Returns:
        Demand multiplier float
    """
    is_weekend = day_of_week >= 5

    # Late night (bar closing time)
    if local_hour in [22, 23, 0, 1, 2]:
        return 1.8 if is_weekend else 1.3

    # Morning rush hour (weekdays only)
    if local_hour in [7, 8, 9] and not is_weekend:
        return 2.2

    # Evening rush hour (weekdays only)
    if local_hour in [17, 18, 19] and not is_weekend:
        return 2.0

    # Lunch hour
    if local_hour in [11, 12, 13]:
        return 1.3

    # Early morning dead zone
    if local_hour in [3, 4, 5]:
        return 0.3

    # Normal daytime
    return 1.0


# =============================================================================
# WEATHER MULTIPLIERS
# =============================================================================

def get_weather_multiplier(weather_severity: int) -> float:
    """
    Calculate demand multiplier based on weather severity.

    Args:
        weather_severity: 1=clear, 2=cloudy, 3=rain, 4=heavy rain, 5=storm

    Returns:
        Demand multiplier float
    """
    multipliers = {
        1: 1.0,   # clear
        2: 1.1,   # cloudy
        3: 1.5,   # rain
        4: 1.9,   # heavy rain
        5: 2.3,   # storm
    }
    return multipliers.get(weather_severity, 1.0)


def get_supply_factor(
    weather_severity: int,
    local_hour: int,
    day_of_week: int,
) -> float:
    """
    Calculate supply reduction factor based on conditions.

    Args:
        weather_severity: 1-5 weather scale
        local_hour: Local hour (0-23)
        day_of_week: 0=Monday, 6=Sunday

    Returns:
        Supply factor (multiplied against base driver count)
    """
    factor = 1.0

    # Weather reduces supply
    if weather_severity == 3:
        factor *= settings.supply.rain_factor
    elif weather_severity == 4:
        factor *= settings.supply.heavy_rain_factor
    elif weather_severity == 5:
        factor *= settings.supply.snow_factor

    # Late night reduces supply
    if local_hour in [22, 23, 0, 1, 2, 3]:
        factor *= settings.supply.late_night_factor

    # Rush hour increases supply
    elif local_hour in [7, 8, 9, 17, 18, 19] and day_of_week < 5:
        factor *= settings.supply.rush_hour_factor

    # Weekend nights reduce supply
    if day_of_week >= 5 and local_hour in [21, 22, 23, 0, 1, 2]:
        factor *= settings.supply.weekend_night_factor

    return max(factor, 0.1)  # never below 10% of base supply


# =============================================================================
# HOLIDAY MULTIPLIERS
# =============================================================================

def get_holiday_multiplier(current_date: object) -> float:
    """
    Calculate demand multiplier based on holidays.

    Args:
        current_date: datetime.date object

    Returns:
        Demand multiplier float
    """
    try:
        import holidays as hd
        from datetime import timedelta

        us_holidays = hd.US()

        # Check if today is a holiday
        if current_date in us_holidays:
            return settings.holidays.demand_multiplier

        # Check if tomorrow is a holiday (holiday eve)
        tomorrow = current_date + timedelta(days=1)
        if tomorrow in us_holidays:
            return settings.holidays.eve_demand_multiplier

    except Exception as e:
        logger.warning(f"Holiday check failed: {e}")

    return 1.0


# =============================================================================
# SPECIAL EVENTS
# =============================================================================

class EventManager:
    """
    Manages simulated special events (concerts, sports games).

    Events start randomly based on probability and last a random duration.
    Each active event boosts demand in its zone by a random multiplier.
    """

    def __init__(self) -> None:
        self.active_events: dict[str, dict] = {}

    def update_events(self, zone_id: str, current_time: datetime) -> tuple[bool, float]:
        """
        Update event state for a zone and return event multiplier.

        Args:
            zone_id: The zone to check/update
            current_time: Current datetime

        Returns:
            Tuple of (is_event_active, demand_multiplier)
        """
        # Check if existing event has expired
        if zone_id in self.active_events:
            event = self.active_events[zone_id]
            if current_time >= event["end_time"]:
                del self.active_events[zone_id]
                logger.info(f"Event ended in zone {zone_id}")

        # Maybe start a new event
        if zone_id not in self.active_events:
            # Convert hourly probability to per-second
            prob_per_second = settings.events.probability / 3600
            if random.random() < prob_per_second:
                from datetime import timedelta
                duration = random.randint(
                    settings.events.min_duration_minutes,
                    settings.events.max_duration_minutes,
                )
                multiplier = random.uniform(
                    settings.events.min_demand_multiplier,
                    settings.events.max_demand_multiplier,
                )
                self.active_events[zone_id] = {
                    "end_time": current_time + timedelta(minutes=duration),
                    "multiplier": multiplier,
                }
                logger.info(
                    f"New event in zone {zone_id}: "
                    f"{multiplier:.1f}x demand for {duration} minutes"
                )

        if zone_id in self.active_events:
            return True, self.active_events[zone_id]["multiplier"]

        return False, 1.0


# =============================================================================
# MAIN SIMULATOR
# =============================================================================

class RideSimulator:
    """
    Main ride request event simulator.

    Generates realistic ride request events across 3 cities and 50 zones,
    accounting for time patterns, weather, holidays, and special events.
    """

    def __init__(self) -> None:
        self.cities = settings.cities
        self.all_zones: list[dict] = []
        self.event_manager = EventManager()
        self.weather_cache: dict[str, dict] = {}
        self._initialize_zones()
        logger.info(
            f"RideSimulator initialized: "
            f"{len(self.cities)} cities, "
            f"{len(self.all_zones)} zones"
        )

    def _initialize_zones(self) -> None:
        """Generate all zones for all cities."""
        for city in self.cities:
            city_zones = generate_zones(city)
            self.all_zones.extend(city_zones)
            logger.info(f"Generated {len(city_zones)} zones for {city.name}")

    def update_weather(self, city_name: str, weather_severity: int) -> None:
        """
        Update cached weather for a city.

        Called by weather_client.py every 10 minutes.

        Args:
            city_name: City identifier string
            weather_severity: 1-5 severity scale
        """
        self.weather_cache[city_name] = {
            "severity": weather_severity,
            "updated_at": datetime.now(),
        }

    def _get_weather_severity(self, city_name: str) -> int:
        """Get current weather severity for a city, default to clear."""
        if city_name in self.weather_cache:
            return self.weather_cache[city_name]["severity"]
        return 1  # default: clear weather

    def _calculate_zone_demand(
        self,
        zone: dict,
        city_config: object,
        local_dt: datetime,
        weather_severity: int,
        holiday_multiplier: float,
    ) -> int:
        """
        Calculate demand for a single zone at the current moment.

        Combines all multipliers: base × time × weather × event × holiday × spike

        Args:
            zone: Zone dictionary with zone_id and city
            city_config: CityConfig object
            local_dt: Current datetime in city's local timezone
            weather_severity: 1-5 weather scale
            holiday_multiplier: 1.0 or higher on holidays

        Returns:
            Integer demand count (events per second for this zone)
        """
        local_hour = local_dt.hour
        day_of_week = local_dt.weekday()

        # Base demand for this city
        base = city_config.base_demand / city_config.num_zones

        # Apply multipliers
        time_mult = get_time_multiplier(local_hour, day_of_week)
        weather_mult = get_weather_multiplier(weather_severity)
        is_event, event_mult = self.event_manager.update_events(
            zone["zone_id"], local_dt
        )
        holiday_mult = holiday_multiplier

        # Random spike (5% chance per zone per second)
        spike_mult = (
            random.uniform(1.5, 3.0)
            if random.random() < settings.simulator.demand_spike_probability
            else 1.0
        )

        # Calculate final demand
        raw_demand = (
            base
            * time_mult
            * weather_mult
            * event_mult
            * holiday_mult
            * spike_mult
        )

        # Add random noise ±20%
        noise = random.uniform(0.8, 1.2)
        final_demand = max(1, int(raw_demand * noise))

        return final_demand

    def _calculate_zone_supply(
        self,
        weather_severity: int,
        local_hour: int,
        day_of_week: int,
    ) -> int:
        """
        Calculate available driver supply for a zone.

        Args:
            weather_severity: 1-5 weather scale
            local_hour: Local hour (0-23)
            day_of_week: 0=Monday, 6=Sunday

        Returns:
            Integer driver count
        """
        base = settings.supply.base_drivers_per_zone
        factor = get_supply_factor(weather_severity, local_hour, day_of_week)
        noise = random.uniform(0.85, 1.15)
        return max(1, int(base * factor * noise))

    def generate_events(self) -> Generator[list[dict], None, None]:
        """
        Continuously generate batches of ride request events.

        Yields:
            List of event dictionaries (one batch per yield)
        """
        logger.info(
            f"Starting event generation: "
            f"{settings.simulator.events_per_second} events/sec"
        )

        while True:
            batch_start = time.time()
            batch: list[dict] = []

            # Get current time for each city
            city_local_times = {}
            holiday_multipliers = {}

            for city_config in self.cities:
                tz = pytz.timezone(city_config.timezone)
                local_dt = datetime.now(tz)
                city_local_times[city_config.name] = local_dt
                holiday_multipliers[city_config.name] = get_holiday_multiplier(
                    local_dt.date()
                )

            # Generate events for each zone
            events_per_zone = max(
                1,
                settings.simulator.events_per_second // len(self.all_zones),
            )

            for zone in self.all_zones:
                city_name = zone["city"]
                city_config = next(
                    c for c in self.cities if c.name == city_name
                )
                local_dt = city_local_times[city_name]
                weather_severity = self._get_weather_severity(city_name)
                holiday_mult = holiday_multipliers[city_name]

                demand = self._calculate_zone_demand(
                    zone,
                    city_config,
                    local_dt,
                    weather_severity,
                    holiday_mult,
                )
                supply = self._calculate_zone_supply(
                    weather_severity,
                    local_dt.hour,
                    local_dt.weekday(),
                )

                # Generate individual events for this zone
                zone_events = min(demand, events_per_zone * 3)
                for _ in range(zone_events):
                    # Small random offset within zone
                    lat_offset = random.uniform(-0.005, 0.005)
                    lon_offset = random.uniform(-0.005, 0.005)

                    event = {
                        "event_id": str(uuid.uuid4()),
                        "zone_id": zone["zone_id"],
                        "city": city_name,
                        "latitude": zone["latitude"] + lat_offset,
                        "longitude": zone["longitude"] + lon_offset,
                        "timestamp_ms": int(local_dt.timestamp() * 1000),
                        "available_drivers": supply,
                        "weather_severity": weather_severity,
                        "demand_count": demand,
                    }
                    batch.append(event)

            # Yield batch
            yield batch

            # Sleep to maintain target rate
            elapsed = time.time() - batch_start
            sleep_time = max(0, 1.0 - elapsed)
            if sleep_time > 0:
                time.sleep(sleep_time)